opt_in_rules:
  - all

disabled_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - attributes
  - closure_body_length
  - contrasted_opening_brace
  - cyclomatic_complexity
  - discouraged_none_name
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - file_header
  - file_length
  - file_name
  - file_types_order
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - identifier_name
  - implicit_optional_initialization
  - implicitly_unwrapped_optional
  - line_length
  - missing_docs
  - nesting
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - number_separator
  - one_declaration_per_file
  - opening_brace
  - prefer_condition_list
  - prefixed_toplevel_constant
  - redundant_self_in_closure
  - redundant_type_annotation
  - required_deinit
  - sorted_enum_cases
  - switch_case_alignment
  - todo
  - trailing_comma
  - type_body_length
  - type_contents_order
  - void_function_in_ternary
